export const normalizePathUpdates = <R extends Record<string, unknown> = Record<string, unknown>>(
  values: Record<string, unknown>,
): R => {
  // Generated by Copilot, modified due to TypeScript saying some properties are undefined (mainly the array accessing).
  const isPathBased = Object.keys(values).some((key) => key.includes('.'))
  const errorMessage = 'Invalid path segment in "{path}". Path segments cannot be empty.'

  return isPathBased
    ? (Object.entries(values).reduce<Record<string, unknown>>((acc, [path, value]) => {
        const segments = path.split('.')
        let current = acc

        for (let i = 0; i < segments.length - 1; i++) {
          const segment = segments[i]

          if (!segment) throw new Error(errorMessage.replace('{path}', path))

          if (!current[segment] || typeof current[segment] !== 'object' || Array.isArray(current[segment])) {
            current[segment] = {}
          }

          const existing = current[segment]

          current[segment] =
            typeof existing === 'object' && existing !== null && !Array.isArray(existing) ? { ...existing } : {}

          current = current[segment] as Record<string, unknown>
        }

        const lastSegment = segments[segments.length - 1]
        if (!lastSegment) throw new Error(errorMessage.replace('{path}', path))

        current[lastSegment] = value

        return acc
      }, {}) as R)
    : (values as R)
}
